<a href="https://colab.research.google.com/github/kalebmes/CS376-Machine-Learning/blob/main/Pytorch_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], 
        [3, 4]]

x_data = torch.tensor(data)

In [7]:
np_array = np.array(data)
x2_data = torch.tensor(np_array)
x2_data == torch.from_numpy(np_array)

tensor([[True, True],
        [True, True]])

In [16]:
x_ones = torch.ones_like(x_data)
print(x_ones.type())
torch.from_numpy(np.arange(10)).type()

torch.LongTensor


'torch.LongTensor'

In [29]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
shape = (2, 3)
print(torch.rand(size=(2, 3)))
ones_tensor = torch.ones(shape)
print(ones_tensor.type())
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)

tensor([[0.2538, 0.3047, 0.4569],
        [0.8266, 0.0108, 0.6917]])
torch.FloatTensor
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [50]:
#now let's examine the attribute of a tensor
tensor = torch.rand(3, 4)
print("Our tensor -> ")
print(tensor)
print("Shape of the tensor: ", tensor.shape)
print("Data type of the tensor: ", tensor.dtype)
print("Device the tensor is stored on", tensor.device)

(raws, columns) = tensor.shape
raws, columns

numlist = torch.arange(10)
# numlist[numlist > 5]
tensor[tensor > 0.5]

Our tensor -> 
tensor([[0.9702, 0.6539, 0.2872, 0.6490],
        [0.1461, 0.5827, 0.6314, 0.9448],
        [0.3486, 0.6395, 0.5285, 0.4620]])
Shape of the tensor:  torch.Size([3, 4])
Data type of the tensor:  torch.float32
Device the tensor is stored on cpu


tensor([0.9702, 0.6539, 0.6490, 0.5827, 0.6314, 0.9448, 0.6395, 0.5285])

In [55]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print("My tensor is stord on: ", tensor.device)

In [63]:
my_tensor = torch.zeros((4, 6))
print(my_tensor)

my_tensor[:, 0:-1:2] = 30
print(my_tensor)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[30.,  0., 30.,  0., 30.,  0.],
        [30.,  0., 30.,  0., 30.,  0.],
        [30.,  0., 30.,  0., 30.,  0.],
        [30.,  0., 30.,  0., 30.,  0.]])


In [78]:
t1 = torch.arange(10).reshape(1,10)
t2 = torch.randint(low=0, high=10, size=(1,10))
torch.cat([t1, t2], dim=0)

A = torch.tensor([[1, 2, 3], 
                  [2, 1, 8]])
B = torch.tensor([[3, 5, 9], 
                  [2, 1, 9]])
C = torch.tensor([[1],[2],[3]])
print("A + B: ")
print(A+B)

print("A * B: elementwise")
print(A * B) #same with numpy - * is an elementwise multiplication

print("A * B: matrixmultipliation")
print(torch.matmul(A, B.T))
print(A @ B.T)

A + B: 
tensor([[ 4,  7, 12],
        [ 4,  2, 17]])
A * B: elementwise
tensor([[ 3, 10, 27],
        [ 4,  1, 72]])
A * B: matrixmultipliation
tensor([[40, 31],
        [83, 77]])
tensor([[40, 31],
        [83, 77]])


In [83]:
A.add_(10)
print(A)

tensor([[51, 52, 53],
        [52, 51, 58]])


In [87]:
#so pytorch and numpy can be made to share the same memory location using from_numpy() and numpy() methods
#the former extracts a tensor from a numpy array, and the latter extracts a numpy array from a tensor
numlist = np.arange(10)
my_t = torch.from_numpy(numlist) # share the same memory with 'numlist'
my_t2 = torch.tensor(numlist) #just copies the elements and form the tensor
print(numlist, my_t)

numlist[0] = -12
print(numlist)
print(my_t)
print(my_t2)

my_t3 = torch.arange(10)
nums = my_t3.numpy() # share the memory locaion with 'my_t3'
nums2 = np.array(my_t3) #just creates a numpy array copy with the entries of my_t3
my_t3[0] = 2938
print(nums)
print(my_t3)
print(nums2)

[0 1 2 3 4 5 6 7 8 9] tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
[-12   1   2   3   4   5   6   7   8   9]
tensor([-12,   1,   2,   3,   4,   5,   6,   7,   8,   9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
[2938    1    2    3    4    5    6    7    8    9]
tensor([2938,    1,    2,    3,    4,    5,    6,    7,    8,    9])
[0 1 2 3 4 5 6 7 8 9]


### now we'll take a look at Autograd