<a href="https://colab.research.google.com/github/kalebmes/CS376-Machine-Learning/blob/main/Pytorch_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], 
        [3, 4]]

x_data = torch.tensor(data)

In [7]:
np_array = np.array(data)
x2_data = torch.tensor(np_array)
x2_data == torch.from_numpy(np_array)

tensor([[True, True],
        [True, True]])

In [16]:
x_ones = torch.ones_like(x_data)
print(x_ones.type())
torch.from_numpy(np.arange(10)).type()

torch.LongTensor


'torch.LongTensor'

In [29]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
shape = (2, 3)
print(torch.rand(size=(2, 3)))
ones_tensor = torch.ones(shape)
print(ones_tensor.type())
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)

tensor([[0.2538, 0.3047, 0.4569],
        [0.8266, 0.0108, 0.6917]])
torch.FloatTensor
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [50]:
#now let's examine the attribute of a tensor
tensor = torch.rand(3, 4)
print("Our tensor -> ")
print(tensor)
print("Shape of the tensor: ", tensor.shape)
print("Data type of the tensor: ", tensor.dtype)
print("Device the tensor is stored on", tensor.device)

(raws, columns) = tensor.shape
raws, columns

numlist = torch.arange(10)
# numlist[numlist > 5]
tensor[tensor > 0.5]

Our tensor -> 
tensor([[0.9702, 0.6539, 0.2872, 0.6490],
        [0.1461, 0.5827, 0.6314, 0.9448],
        [0.3486, 0.6395, 0.5285, 0.4620]])
Shape of the tensor:  torch.Size([3, 4])
Data type of the tensor:  torch.float32
Device the tensor is stored on cpu


tensor([0.9702, 0.6539, 0.6490, 0.5827, 0.6314, 0.9448, 0.6395, 0.5285])

In [55]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print("My tensor is stord on: ", tensor.device)

In [63]:
my_tensor = torch.zeros((4, 6))
print(my_tensor)

my_tensor[:, 0:-1:2] = 30
print(my_tensor)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[30.,  0., 30.,  0., 30.,  0.],
        [30.,  0., 30.,  0., 30.,  0.],
        [30.,  0., 30.,  0., 30.,  0.],
        [30.,  0., 30.,  0., 30.,  0.]])


In [78]:
t1 = torch.arange(10).reshape(1,10)
t2 = torch.randint(low=0, high=10, size=(1,10))
torch.cat([t1, t2], dim=0)

A = torch.tensor([[1, 2, 3], 
                  [2, 1, 8]])
B = torch.tensor([[3, 5, 9], 
                  [2, 1, 9]])
C = torch.tensor([[1],[2],[3]])
print("A + B: ")
print(A+B)

print("A * B: elementwise")
print(A * B) #same with numpy - * is an elementwise multiplication

print("A * B: matrixmultipliation")
print(torch.matmul(A, B.T))
print(A @ B.T)

A + B: 
tensor([[ 4,  7, 12],
        [ 4,  2, 17]])
A * B: elementwise
tensor([[ 3, 10, 27],
        [ 4,  1, 72]])
A * B: matrixmultipliation
tensor([[40, 31],
        [83, 77]])
tensor([[40, 31],
        [83, 77]])


In [83]:
A.add_(10)
print(A)

tensor([[51, 52, 53],
        [52, 51, 58]])


In [87]:
#so pytorch and numpy can be made to share the same memory location using from_numpy() and numpy() methods
#the former extracts a tensor from a numpy array, and the latter extracts a numpy array from a tensor
numlist = np.arange(10)
my_t = torch.from_numpy(numlist) # share the same memory with 'numlist'
my_t2 = torch.tensor(numlist) #just copies the elements and form the tensor
print(numlist, my_t)

numlist[0] = -12
print(numlist)
print(my_t)
print(my_t2)

my_t3 = torch.arange(10)
nums = my_t3.numpy() # share the memory locaion with 'my_t3'
nums2 = np.array(my_t3) #just creates a numpy array copy with the entries of my_t3
my_t3[0] = 2938
print(nums)
print(my_t3)
print(nums2)

[0 1 2 3 4 5 6 7 8 9] tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
[-12   1   2   3   4   5   6   7   8   9]
tensor([-12,   1,   2,   3,   4,   5,   6,   7,   8,   9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
[2938    1    2    3    4    5    6    7    8    9]
tensor([2938,    1,    2,    3,    4,    5,    6,    7,    8,    9])
[0 1 2 3 4 5 6 7 8 9]


### now we'll take a look at Autograd

In [88]:
import torchvision
model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1,1000)

Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


  0%|          | 0.00/44.7M [00:00<?, ?B/s]

In [89]:
prediction = model(data) # forward propagation

In [90]:
loss= (prediction - labels).sum()
loss.backward() #backward propagation - now autograd calculates and stores the gradients for each model parameter in the parameter's .grad attribute

In [104]:
#now we'll load an optimizer. in this SGD, with a learning rate of 0.01, and we'll also apply a momentum of 0.9
optim = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)

In [105]:
optim.step() #this initiates the gradient descent

In [123]:
#how does autograd work though? 
a = torch.tensor([2, 3], requires_grad=True, dtype=float)
b = torch.tensor([6, 4], requires_grad=True, dtype=float)
Q = 3*a**3 - b**2
Q.backward(gradient=torch.tensor([1, 1]))

In [124]:
print(b.grad)

tensor([-12.,  -8.], dtype=torch.float64)


## Neural Networks with pytorch

In [ ]:
#let's define the network
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):

  def __init__(self) -> None:
      super(Net, self).__init__()
      #1 input image channel, 6 output image channel and 5x5 square convolution kernel
      self.conv1 = nn.Conv2d(1, 6, 5)
      self.conv2 = nn.Conv2d(6, 16, 5)
      #y = Wx + b
      self.fc1 = nn.Linear(16*5*5, 120)
      self.fc2 = nn.Linear(120, 84)
      self.fc3 = nn.Linear(84, 10)
      